fix AttributeError: 'PhonopyAtoms' object has no attribute 'magnetic_moments' on /pymatgen/io/phonopy.py:51
     @requires(Phonopy, "phonopy not installed!")
    def get_pmg_structure(phonopy_structure):
        ...
        lattice = phonopy_structure.cell
        frac_coords = phonopy_structure.scaled_positions
        symbols = phonopy_structure.symbols
        masses = phonopy_structure.masses
>       mms = phonopy_structure.magnetic_moments