Deprecate `get_string()` methods in favor of `get_str()` (#3231)
* restore accidentally deleted io.core.InputFile.from_string

* add io.core type hints

* deprecate get_string methods in favor of get_str

* replace get_string() calls with get_str()

* fix @classmethod and @deprecate order

causing numpy\lib\utils.py:153: in __call__
    old_name = func.__name__
E   AttributeError: 'classmethod' object has no attribute '__name__'

* LMTOCopl google-style doc str

* fix KeyError and fix >   arr = np.array([round(float(i), sigfigs) for i in fields[f + 1].split()])
E   ValueError: could not convert string to float: '.'