VaspInputSet couldn't write cif structures (#2721)
* cleanup fix for 'AttributeError: 'PosixPath' object has no attribute 'lower'

* add missing arguments to doc strings

Co-authored-by: Janosh Riebesell <janosh.riebesell@gmail.com>